apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
    }
    maven {
        name = 'CleanroomCurseMaven'
        url = 'https://curse.cleanroommc.com'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
    maven {
        name = "ModMaven"
        url  = uri("https://modmaven.dev/")
    }
    mavenCentral()
    mavenLocal()
    maven {
        url = 'https://www.jitpack.io'
    }
}

dependencies {
    compileOnly "com.cleanroommc:sponge-mixin:0.20.12+mixin.0.8.7"
    if (propertyBool('enable_lwjglx')) {
        compileOnly "com.cleanroommc:lwjglx:1.0.0"
    }

    modRuntimeOnly 'curse.maven:fugue-1005815:8403977'
    modRuntimeOnly 'curse.maven:scalar-legacy-1235372:6842491'
    modRuntimeOnly 'org.scala-lang:scala-library:2.12.20'
    modRuntimeOnly 'org.scala-lang:scala-reflect:2.12.20'
    
    //cofhcore
    modCompileOnly "curse.maven:CoFHCore-69162:2920433"
    //crt
    compileOnly 'CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.711'
    // Hwyla
    modCompileOnly "curse.maven:Hwyla-253449:2568751"
    // IndustrialCraft 2
    modCompileOnly "curse.maven:industrial-craft-242638:2746892"
    // HEI
    modImplementation 'mezz:jei:4.34.0'
    // The One Probe
    modImplementation "curse.maven:the-one-probe-245211:2667280"
    //EIO
    modCompileOnly("curse.maven:ender-core-ceu-1530852:8707400")
    modCompileOnly("curse.maven:enderio-ceu-1530854:8707396")
    // Baubles
    modImplementation "curse.maven:baubles-227083:2518667"
    // CodeChickenLib
    modCompileOnly "curse.maven:codechicken-lib-1-8-242818:2779848"
    // Chisel
    modCompileOnly "curse.maven:chisel-235279:2915375"
    // Inventory Tweaks
    modCompileOnly "curse.maven:inventory-tweaks-223094:2923460"
    // Inventory Bogo-Sorter
    modImplementation "curse.maven:inventory-bogosorter-632327:8231600"
    modRuntimeOnly("com.cleanroommc:modularui:3.1.6") {transitive = false}
    modRuntimeOnly "curse.maven:key-binding-patch-928895:5951859"
    // mouse tweaks
    modImplementation "curse.maven:mouse-tweaks-unofficial-461660:5876158"
    // Connected Textures Mod
    modCompileOnly "curse.maven:ctm-267602:2915363"

    modRuntimeOnly("curse.maven:spark-361579:3542217")
    modRuntimeOnly 'curse.maven:thaumcraft-223628:2629023'
    modRuntimeOnly 'curse.maven:itemzoom-261725:2643616'
}
